# roles/bind/vars/Debian.yml
---
bind_packages:
  - python-netaddr
  - bind9
  - bind9utils

bind_service: bind9

# Localhost zone
bind_default_zone_files:
  - named.conf.default-zones

# Main config file
#bind_config: "/srv/docker/bind/bind/etc/named.conf"
bind_conf_dir: "/home/{{ ansible_user }}/docker_compose/bind"
bind_config: "{{ bind_conf_dir }}/etc/named.conf"

# Directory with run-time stuff
bind_dir: "{{ bind_conf_dir }}/lib"
auth_file: "auth_transfer.conf"
bind_auth_file: "{{ bind_conf_dir }}/{{ auth_file }}"

# Docker bind path
bind_zone_dir_docker: "/data/bind/etc"
bind_dir_docker: "/data/bind"
bind_log: "{{ bind_dir_docker }}/lib/named.log"


bind_owner: systemd-resolve
bind_group: systemd-journal

bind_bindkeys_file: "{{ bind_conf_dir }}/etc/named.iscdlv.key"
bind_pid_file: "/run/named/named.pid"
bind_session_keyfile: "/run/named/session.key"

# Custom location for master zone files
bind_zone_dir: "{{ bind_conf_dir }}/etc"
bind_slave_dir: "{{ bind_conf_dir }}/slaves"
