---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install a list of packages
  apt:
    pkg:
     - mc
     - ncdu
     - nload
     - git
     - htop
     - isc-dhcp-server
