---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  tags: server

- name: Install a list of packages
  apt:
    pkg:
      - mc
      - ncdu
      - nload
      - git
      - htop
  tags: server
