---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  tags: server

- name: Install a list of packages
  apt:
    pkg:
      - python3-pip
      - mc
      - ncdu
      - nload
      - git
      - htop
      - rsyslog
      - rsync
  tags: server

- name: Configure rsyslog to send syslog logs to specified host and port
  lineinfile:
    path: "{{ rsyslog_path | default('/etc/rsyslog.d/50-default.conf') }}"
    line: "*.*\ @{{ fluentd_address | default(127.0.0.1) }}:\
          {{ fluentd_port | default(5140) }};RSYSLOG_SyslogProtocol23Format"
    mode: "0644"
