---
- name: Converge
  hosts: all
  become: yes

  pre_tasks:
    - name: Install pip3
      package:
        pkg: "{{ item }}"
        state: present
      with_items:
        - python3-pip

    - name: install python docker
      pip:
        name: docker

  roles:
    - role: geerlingguy.docker
    - role: systemd
