def_lease_time: "600"
max_lease_time: 7200
subnet: 192.168.1.0
subnet_net_mask: 255.255.255.0
start_address: 192.168.1.110
end_address: 192.168.1.220
router_address: 192.168.1.1
dns_address: 192.168.1.1

#ssh config
sshd_use_pam: "no"
sshd_password_authentication: "no"
sshd_challenge_response_authentication: "no"
sshd_permitroot_login: "no"
#ftp ssl cert
rsa_cert_file: "/etc/ssl/certs/vsftpd.pem"
rsa_private_key_file: "/etc/ssl/certs/vsftpd.pem"

netplan_configuration:
    network:
        version: 2
        ethernets:
            eth0:
                dhcp4: no
                dhcp6: no
                addresses: ["192.168.1.246/16"]
                gateway4: '192.168.1.1'
                nameservers:
                    addresses: ["192.168.1.1"]
