# Network configuration
netplan_configuration:
    network:
        version: 2
        ethernets:
            eth0:
                dhcp4: no
                dhcp6: no
                addresses: ["192.168.42.27/24"]
                gateway4: '192.168.42.129'
                nameservers:
                    addresses: ["192.168.42.129", "8.8.8.8"]

#ssh config
sshd_use_pam: "no"
sshd_password_authentication: "no"
sshd_challenge_response_authentication: "no"
sshd_permitroot_login: "no"

#Firewall config
firewall_allowed_tcp_ports:
  - "53"   # TCP
  - "22"   # ssh
  - "25"   # smtp
  - "80"   # http
  - "443"  # https
  - "25"   # smtp
  - "465"  # smtps
  - "587"  # STARTTLS
  - "110"  # POP3
  - "995"  # POP3S
  - "143"  # IMAP
  - "993"  # IMAPS
firewall_allowed_udp_ports:
  - "53"   # dns

                    
docker_users: dep7admin

#ftp ssl cert
rsa_cert_file: "/etc/ssl/certs/vsftpd.pem"
rsa_private_key_file: "/etc/ssl/certs/vsftpd.pem"

# DNS Server settings
# Main config file
bind_conf_dir: "/home/{{ ansible_user }}/docker_compose/bind"
bind_config: "{{ bind_conf_dir }}/etc/named.conf"

# Docker bind path
bind_zone_dir_docker: "/data/bind/etc"
bind_dir_docker: "/data/bind"
bind_log: "{{ bind_dir_docker }}/lib/named.log"

bind_zone_file_mode: '0775'
bind_allow_query:
  - any
bind_listen_ipv4:
  - any
bind_listen_ipv6:
  - any
bind_acls:
  - name: acl1
    match_list:
      - 172.17.0.0/16
      - 192.168.42.0/24
bind_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'
bind_recursion: false
bind_query_log: 
  file: '{{ bind_dir_docker }}/lib/query.log'
  versions: 100
  size: 20m
bind_other_logs:
  - name: resolver
    file: '{{ bind_dir_docker }}/lib/auth_servers.log'
    versions: 50
    size: 20m
  - name: query-errors
    file: '{{ bind_dir_docker }}/lib/query-errors.log'
    versions: 5
    size: 20m
bind_check_names: "master ignore"
bind_zone_master_server_ip: "{{ ansible_default_ipv4.address }}"
bind_zone_minimum_ttl: "2D"
bind_zone_ttl: "2W"
bind_zone_time_to_refresh: "2D"
bind_zone_time_to_retry: "2H"
bind_zone_time_to_expire: "2W"
bind_zone_domains:
  - name: 'dep7serverm.com'
    networks:
      - '192.168.1'
    name_servers:
      - dep7serverm.com.
    hostmaster_email: rand.dep7serverm.com
    hosts:
      - name: mail
        ip: 192.168.1.142
      - name: jenkins
        ip: 192.168.1.143
      - name: repo
        ip: 192.168.1.144
      - name: "@"
        ip: 192.168.1.142
    mail_servers:
      - name: mail
        preference: 10

#Docker-compose settings
docker_compose_owner: "{{ ansible_user }}"
docker_compose_owner_group: "{{ ansible_user }}"
docker_compose_dst: /home/{{ ansible_user }}/

#Service config
docker_subnet: 172.19.0.0/16
# Docker-compose.yml
keep_logs_day: 2
chat_admin_name: admin
chat_admin_pass: changeme
chat_admin_mail: "admin@dep7serverm.com"
elastic_pass   : "changeme"
gitlab_external_url: "https://dep7serverm.com/gitlab"
# Mailu.env
SECRET_KEY:           6ABWHB8XWHZ6RVDM
domain:               "dep7serverm.com"
hostnames:            "mail.dep7serverm.com"
sitename:             dep7serverm
website:              "https://dep7serverm.com"
mail_admin_name:      admin
mail_admin_mailhost:  "dep7serverm.com"
mail_admin_pass:      changeme

# Not used now
#Docker compose vars for systemd
unit_config:
  - name: rocketchat
    Unit: 
      Description: Docker compose application service
      Requires: docker.service
      After: docker.service
    Service:
      Type: oneshot
      RemainAfterExit: yes
      WorkingDirectory: /home/{{ ansible_user }}/
      ExecStart: /usr/local/bin/docker-compose up -d
      ExecStop: /usr/local/bin/docker-compose down
      TimeoutStartSec: 0
    Install:
       WantedBy: multi-user.target


#Prometheus node exporter
node_exporter_web_listen_address: "{{ ansible_default_ipv4.address }}:9100"

#DHCP settings
def_lease_time: "600"
max_lease_time: 7200
subnet: 192.168.1.0
subnet_net_mask: 255.255.255.0
start_address: 192.168.1.110
end_address: 192.168.1.220
router_address: 192.168.1.1
dns_address: 192.168.1.1