# Network configuration
netplan_configuration:
    network:
        version: 2
        ethernets:
            eth0:
                dhcp4: no
                dhcp6: no
                addresses: ["192.168.42.27/24"]
                gateway4: '192.168.42.129'
                nameservers:
                    addresses: ["192.168.42.129", "8.8.8.8"]
                    
docker_users: dep7admin

#DHCP settings
def_lease_time: "600"
max_lease_time: 7200
subnet: 192.168.1.0
subnet_net_mask: 255.255.255.0
start_address: 192.168.1.110
end_address: 192.168.1.220
router_address: 192.168.1.1
dns_address: 192.168.1.1

#ssh config
sshd_use_pam: "no"
sshd_password_authentication: "no"
sshd_challenge_response_authentication: "no"
sshd_permitroot_login: "no"
#ftp ssl cert
rsa_cert_file: "/etc/ssl/certs/vsftpd.pem"
rsa_private_key_file: "/etc/ssl/certs/vsftpd.pem"

# DNS Server settings
bind_zone_file_mode: '0775'
bind_allow_query:
  - any
bind_listen_ipv4:
  - any
bind_listen_ipv6:
  - any
bind_acls:
  - name: acl1
    match_list:
      - 172.17.0.0/16
      - 192.168.1.0/24
bind_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'
bind_recursion: false
bind_query_log: 
  file: '/data/bind/lib/query.log'
  versions: 100
  size: 20m
bind_other_logs:
  - name: resolver
    file: '/data/bind/lib/auth_servers.log'
    versions: 50
    size: 20m
  - name: query-errors
    file: '/data/bind/lib/query-errors.log'
    versions: 5
    size: 20m
bind_check_names: "master ignore"
bind_zone_master_server_ip: "192.168.1.248"
bind_zone_minimum_ttl: "2D"
bind_zone_ttl: "2W"
bind_zone_time_to_refresh: "2D"
bind_zone_time_to_retry: "2H"
bind_zone_time_to_expire: "2W"
bind_zone_domains:
  - name: 'dep7server.com'
    networks:
      - '192.168.1'
    name_servers:
      - dep7server.com.
    hostmaster_email: rand.dep7mail.com
    hosts:
      - name: mail
        ip: 192.168.1.142
      - name: jenkins
        ip: 192.168.1.143
      - name: repo
        ip: 192.168.1.144
      - name: "@"
        ip: 192.168.1.142
    mail_servers:
      - name: mail
        preference: 10

#Docker compose vars for systemd
unit_config:
  - name: rocketchat
    Unit: 
      Description: Docker compose application service
      Requires: docker.service
      After: docker.service
    Service:
      Type: oneshot
      RemainAfterExit: yes
      WorkingDirectory: /home/{{ ansible_user }}/
      ExecStart: /usr/local/bin/docker-compose up -d
      ExecStop: /usr/local/bin/docker-compose down
      TimeoutStartSec: 0
    Install:
       WantedBy: multi-user.target

docker_compose_owner: "{{ ansible_user }}"
docker_compose_owner_group: "{{ ansible_user }}"
docker_compose_dst: /home/{{ ansible_user }}/

#Prometheus node exporter
node_exporter_web_listen_address: "{{ ansible_default_ipv4.address }}:9100"