- hosts: dep7server
  become: yes

  vars_files:
    #- ~/VSCode/ansible/dep7server_m/dep7server_vault.yml 
    - ~/work/ansible/server_m/dep7server_vault.yml
  vars:
    ansible_become_pass: '{{ dep7server_password }}'

  roles:
    #- set_up_network
    #- geerlingguy.firewall
    #- copy_ssh_key
    #- set_up_server
    - geerlingguy.docker
    #- set_up_dhcp
    #- set_up_ftp
    #- bind9-dns
    - docker-compose_add

