---
- name: Converge
  hosts: all
  become: yes
  vars:
    ansible_user: root
  pre_tasks:
    - name: Install BIND
      package:
        pkg: "{{ item }}"
        state: present
      with_items:
        - "{{ bind_packages }}"
        - python3-pip

    - name: install python docker
      pip:
        name: docker

  roles:
    - role: geerlingguy.docker
    - role: docker-compose_add
