---
- name: Converge
  hosts: all
  become: yes
  vars:
    ansible_user: root
  pre_tasks:
    - name: Install pip
      package:
        pkg: "{{ item }}"
        state: present
      with_items:
        - python3-pip

    - name: install python docker
      pip:
        name:
          - docker
          - docker-compose

  roles:
    - role: geerlingguy.docker
    - role: docker-compose_add
