---
- name: Converge
  hosts: all
  become: yes
  vars:
    ansible_user: root
    docker_users: root

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes

    - name: Install packages
      apt:
        pkg: ['python3-pip', 'rsync']
        state: present

  roles:
    - role: geerlingguy.docker
    - role: docker-compose_add
