---
docker_compose_network: "172.19.0.0/24"
docker_compose_env: docker-compose.env
mail_server_domain: dep7serverm.com
mail_server_hostnames: mail.dep7serverm.com
TLS_FLAVOR: "cert"
webmail: roundcube
webdav: radicale
mail_antivirus: clamav
mail_sitename: dep7serverm
mail_website: "https://dep7serverm.com"
docker_compose_path: /home/{{ ansible_user }}/docker_compose/docker-compose.yml
docker_compose_env_path: /home/{{ ansible_user }}/docker_compose/mail/mailu.env
compose_dir: /home/{{ ansible_user }}/docker_compose
volume_dir: /home/{{ ansible_user }}/mailu
mail_cert_dir: "{{ compose_dir }}/mail/certs"
mail_domain: "dep7serverm.com"
admin_mail_name: "rand"

services_paths:
  - path: "/home/{{ ansible_user }}/docker_compose/monitoring/prometheus"
    mode: "0777"
  - path: "/home/{{ ansible_user }}/docker_compose/monitoring/prometheus/prometheus_data"
    mode: "0777"
  - path: "/home/{{ ansible_user }}/docker_compose/monitoring/grafana"
    mode: "0777"
  - path: "/home/{{ ansible_user }}/docker_compose/monitoring/grafana/grafana_data"
    mode: "0777"
  - path: "/home/{{ ansible_user }}/docker_compose/mail"
    mode: "0777"
  - path: "/home/{{ ansible_user }}/docker_compose/mail/data"
    mode: "0750"
  - path: "/home/{{ ansible_user }}/docker_compose/logging/elasticsearch/data"
    mode: "0777"
