---
- name: Install dhcp server
  apt:
    pkg:
      - isc-dhcp-server
  tags: dhcp

- include_tasks: default-fix.yml
  when: ansible_os_family == 'Debian'
  tags: dhcp

- name: Set config directory perms
  file:
    path: "{{ dhcp_config | dirname }}"
    state: directory
    mode: '0755'
  tags: dhcp

- name: Configure dhcp server
  template:
    src: dhcp_setup.j2
    dest: "{{ dhcp_config }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart dhcp
  tags: dhcp
