# roles/bind/defaults/main.yml
---

bind_log: "{{ bind_dir }}/named.log"

bind_zone_domains:
  - name: "dep7serverm.com"
    hostmaster_email: "randsw@dep7serverm.com"
    networks:
      - "129.200.9"

# List of acls.
bind_acls:
  - "129.200.9.0/24"
  - "172.17.0.0/16"
  - "127.0.0.1"

# Key binding for slaves
bind_dns_keys:
  - name: master_key
    algorithm: hmac-sha256
    secret: "azertyAZERTY123456"

# List of IPv4 address of the network interface(s) to listen on. Set to "any"
# to listen on all interfaces
bind_listen_ipv4:
  - "any"

# List of IPv6 address of the network interface(s) to listen on.
bind_listen_ipv6:
  - "::1"

# List of hosts that are allowed to query this DNS server.
bind_allow_query:
  - "localhost"

# Determines whether recursion should be allowed. Typically, an authoritative
# name server should have recursion turned OFF.
bind_recursion: false
bind_allow_recursion:
  - "any"

# Allows BIND to be set up as a caching name server
bind_forward_only: false

# List of name servers to forward DNS requests to.
bind_forwarders: []

# DNS round robin order (random or cyclic)
bind_rrset_order: "random"

# statistics channels configuration
bind_statistics_channels: false
bind_statistics_port: 8053
bind_statistics_host: 127.0.0.1
bind_statistics_allow:
  - "127.0.0.1"

# DNSSEC configuration
bind_dnssec_enable: true
bind_dnssec_validation: auto

bind_extra_include_files: []

# SOA information
bind_zone_ttl: "1W"
bind_zone_time_to_refresh: "1D"
bind_zone_time_to_retry: "1H"
bind_zone_time_to_expire: "1W"
bind_zone_minimum_ttl: "1D"

# File mode for master zone files (needs to be something like 0660 for dynamic updates)
bind_zone_file_mode: "0775"

#DNS config patch
DNS_path:
  - path: "/home/{{ ansible_user }}/docker_compose/bind"
    mode: "0775"
    user: systemd-network
    group: systemd-journal
  - path: "/home/{{ ansible_user }}/docker_compose/bind/etc"
    mode: "2775"
    user: systemd-network
    group: systemd-journal
  - path: "/home/{{ ansible_user }}/docker_compose/bind/lib"
    mode: "0755"
    user: systemd-network
    group: systemd-journal
