---
- name: Run the equivalent of "apt-get update" as a separate step # delete after test
  apt:
    update_cache: yes

- name: Install a list of packages # delete after test
  apt:
    pkg:
      - python3-pip

- name: Install python packages for docker
  pip:
    name:
      - docker
      - docker-compose

- name: Create a directory for compose
  file:
    path: "{{ compose_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'

- name: create dir for docker persistent data
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  loop: "{{ services_paths }}"

- name: Create a directory for mail certs
  file:
    path: "{{ mail_cert_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '0755'

- name: Copy file with owner and permissions
  copy:
    src: "{{ item }}"
    dest: "{{ mail_cert_dir }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_items:
    - cert.pem
    - key.pem

#Try generate cert with ansible module
# - name: Generate a Self Signed OpenSSL certificate.
#   openssl_certificate:
#     path: "{{ openssl_certs_path }}/{{ item.name }}.crt"
#     privatekey_path: "{{ openssl_keys_path }}/{{ item.name }}.key"
#     csr_path: "{{ openssl_csrs_path }}/{{ item.name }}.csr"
#     provider: selfsigned
#   with_items: "{{ openssl_self_signed }}"

- name: Configure docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Configure docker compose env file
  template:
    src: mailu.env.j2
    dest: "{{ docker_compose_env_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Restart docker #https://stackoverflow.com/questions/38087027/docker-compose-stuck-downloading-or-pulling-fs-layer
  service:
    name: docker
    state: restarted
  changed_when: false

- name: Docker-Compose UP
  docker_compose:
    project_src: "{{ compose_dir }}"

- name: Create admin account
  command: "docker-compose exec admin flask mailu admin {{ admin_mail_name }} {{ mail_domain }} {{ dep7server_password }}"
  args:
    chdir: "{{ compose_dir }}"
  changed_when: false
  register: admin_create
  ignore_errors: True

- name: Debug admin create
  debug:
    msg: "{{ admin_create }}"
