---
firewall_state: started
firewall_enabled_at_boot: true

firewall_flush_rules_and_chains: true

firewall_allowed_tcp_ports:
  - "22" #ssh
  - "25" #smtp
  - "80" #http
  - "443" #https
firewall_allowed_udp_ports: 
  - "53" #dns
firewall_forwarded_tcp_ports: []
firewall_forwarded_udp_ports: []
firewall_additional_rules:
  # Passive ftp input rule
  - "iptables -A INPUT -p tcp -m tcp --dport 20 -m conntrack \
     --ctstate NEW,ESTABLISHED -j ACCEPT"
  - "iptables -A INPUT -p tcp -m tcp --dport 21 -m conntrack \
     --ctstate NEW,ESTABLISHED -j ACCEPT"
  - "iptables -A INPUT -p tcp -m tcp --sport 1024:65535 --dport \
     20:65535 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT"
  - "iptables -A -p tcp -m state --state ESTABLISHED -j ACCEPT"
  # Passive ftp output rules
  - "iptables -A OUTPUT -p tcp -m tcp --dport 20 -m conntrack \
     --ctstate NEW,ESTABLISHED -j ACCEPT"
  - "iptables -A OUTPUT -p tcp -m tcp --dport 21 -m conntrack \
     --ctstate NEW,ESTABLISHED -j ACCEPT"
  - "iptables -A OUTPUT -p tcp -m tcp --sport 1024:65535 --dport \
     20:65535 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT"


firewall_enable_ipv6: true
firewall_ip6_additional_rules: []
firewall_log_dropped_packets: true

# Set to true to ensure other firewall management software is disabled.
firewall_disable_firewalld: false
firewall_disable_ufw: false
