---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  #name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    box: geerlingguy/ubuntu1804
    memory: 1024
    cpus: 2
  # - name: instance
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
  lint:
    name: flake8
