---
prod_server:
  hosts:
    dep7server:
      ansible_host: 192.168.42.27
      ansible_user: dep7admin
      ansible_ssh_private_key_file: ~/.ssh/dep7server_m
      ansible_python_interpreter: /usr/bin/python3

