---
prod_server:
  hosts:
    dep7server:
      ansible_host: 192.168.1.247
      ansible_user: dep7admin
      ansible_ssh_private_key_file: ~/.ssh/dep7server_m
      #ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

